# Generated by Django 3.1.4 on 2020-12-31 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsuser',
            options={'ordering': ['username'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'ordering': ['created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=460)),
                ('answer_one', models.CharField(max_length=460)),
                ('answer_two', models.CharField(max_length=460)),
                ('answer_three', models.CharField(max_length=460)),
                ('answer_four', models.CharField(max_length=460)),
                ('right_answer', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four')])),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures', verbose_name='picture')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_questions', to='tests.test')),
            ],
        ),
        migrations.CreateModel(
            name='PassedTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_answers_count', models.PositiveIntegerField()),
                ('question_count', models.PositiveIntegerField()),
                ('pass_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('passed_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test')),
                ('tests_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pass_date_time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=460)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_comments', to='tests.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='testsuser',
            name='tests',
            field=models.ManyToManyField(related_name='users_who_passed_test', through='tests.PassedTests', to='tests.Test'),
        ),
    ]
