# Generated by Django 3.1.4 on 2020-12-31 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20201231_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passedtests',
            options={'ordering': ['pass_date_time'], 'verbose_name': 'Passed test', 'verbose_name_plural': 'Passed tests'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['test', 'text'], 'verbose_name': 'Passed test', 'verbose_name_plural': 'Passed tests'},
        ),
    ]
