# Generated by Django 3.1.4 on 2020-12-31 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20201231_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Passed test', 'verbose_name_plural': 'Passed tests'},
        ),
    ]
