# Generated by Django 3.1.4 on 2020-12-31 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20201231_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['test', 'text'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
