# Generated by Django 3.1.4 on 2021-01-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_auto_20210101_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuser',
            name='avatar',
            field=models.ImageField(blank=True, default='static/', null=True, upload_to='avatars', verbose_name='avatar'),
        ),
    ]
