# Generated by Django 3.1.4 on 2021-01-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_auto_20210105_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuser',
            name='avatar',
            field=models.ImageField(blank=True, default='static/default_avatar.png', null=True, upload_to='avatars', verbose_name='avatar'),
        ),
    ]
