# Generated by Django 3.1.4 on 2021-01-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_auto_20210105_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
