# Generated by Django 3.1.4 on 2021-01-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_test_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
