# Generated by Django 3.1.4 on 2021-01-13 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_auto_20210112_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='picture',
        ),
    ]
