# Generated by Django 3.1.4 on 2021-01-13 10:26

from django.db import migrations

tests_data = [
    {
        "title": "Math basic 1 ",
        "description": "Math basic test _",
        "draft": False,
        "questions": [
            {
                "text": "7 * 8 = ?",
                "answer_one": "56",
                "answer_two": "5",
                "answer_three": "6",
                "answer_four": "78",
                "right_answer": 1,
                "picture": "",
                "test": 1

            },
            {
                "text": "7 * 7 = ?",
                "answer_one": "49",
                "answer_two": "47",
                "answer_three": "77",
                "answer_four": "7",
                "right_answer": 1,
                "picture": "",
                "test": 1

            },
            {
                "text": "12 / 4 = ?",
                "answer_one": "3",
                "answer_two": "33",
                "answer_three": "4",
                "answer_four": "6",
                "right_answer": 1,
                "picture": "",
                "test": 1

            },
            {
                "text": "6 - 5 = ?",
                "answer_one": "1",
                "answer_two": "2",
                "answer_three": "65",
                "answer_four": "22",
                "right_answer": 1,
                "picture": "",
                "test": 1

            },
            {
                "text": "9 / 3 = ?",
                "answer_one": "3",
                "answer_two": "56",
                "answer_three": "49.7",
                "answer_four": "11",
                "right_answer": 1,
                "picture": "",
                "test": 1

            }
        ]

    },
    {
        "title": "Simple  math",
        "description": "Simple test",
        "draft": False,
        "questions": [
            {

                "text": "7 * 3 = ?",
                "answer_one": "56",
                "answer_two": "21",
                "answer_three": "6",
                "answer_four": "78",
                "right_answer": 2,
                "test": 2

            },
            {
                "text": "5 * 7 = ?",
                "answer_one": "49",
                "answer_two": "35",
                "answer_three": "77",
                "answer_four": "7",
                "right_answer": 2,
                "test": 2

            },
            {
                "text": "15 / 5 = ?",
                "answer_one": "3",
                "answer_two": "33",
                "answer_three": "4",
                "answer_four": "6",
                "right_answer": 1,
                "test": 2

            },
            {
                "text": "10 * 5 = ?",
                "answer_one": "1",
                "answer_two": "2",
                "answer_three": "50",
                "answer_four": "22",
                "right_answer": 3,
                "test": 2
            },
            {
                "text": "9 * 9 = ?",
                "answer_one": "3",
                "answer_two": "56",
                "answer_three": "49",
                "answer_four": "81",
                "right_answer": 4,
                "test": 2
            }
        ]

    },

]


def create_questions():
    pass


def create_tests(apps, schema_editor):
    Test = apps.get_model('tests', 'Test')
    Question = apps.get_model('tests', 'Question')
    User = apps.get_model('tests', 'TestsUser')
    author = User.objects.get(id=1)
    for item in tests_data:
        test = Test.objects.get_or_create(
            title=item.get('title'),
            description=item.get('description'),
            draft=item.get('draft'),
            author=author,
        )
        for question in item.get('questions'):
            Question.objects.get_or_create(
                text=question.get('text'),
                answer_one=question.get('answer_one'),
                answer_two=question.get('answer_two'),
                answer_three=question.get('answer_three'),
                answer_four=question.get('answer_four'),
                right_answer=question.get('right_answer'),
                test=test[0]
            )


class Migration(migrations.Migration):
    dependencies = [
        ('tests', '0013_remove_question_picture'),
    ]

    operations = [
        migrations.RunPython(create_tests),
    ]
